### ISSUE TITLE
errs.join is not a function

### ISSUE THREAD

**Issue by towa48** [sindresorhus/gulp-traceur#67]
/home/user/project/node_modules/gulp-traceur/index.js:40
			this.emit('error', new gutil.PluginError('gulp-traceur', errs.join('\n'), {
			                                                              ^

TypeError: errs.join is not a function
    at DestroyableTransform._transform (/home/user/project/node_modules/gulp-traceur/index.js:40:66)
    at DestroyableTransform.Transform._read (/home/user/project/node_modules/gulp-traceur/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/user/project/node_modules/gulp-traceur/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/user/project/node_modules/gulp-traceur/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/user/project/node_modules/gulp-traceur/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/user/project/node_modules/gulp-traceur/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/user/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/user/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/user/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)

**Comment by towa48** [comment]
gulp-traceur/index.js replace
```javascript
} catch (errs) {
	this.emit('error', new gutil.PluginError('gulp-traceur', errs.join('\n'), {
		fileName: file.path,
		showStack: false
}));
```
with this
```javascript
} catch (e) {
	this.emit('error', new gutil.PluginError('gulp-traceur', e.errors.join('\n'), {
		fileName: file.path,
		showStack: false
}));
```
or this
```javascript
} catch (e) {
	this.emit('error', new gutil.PluginError('gulp-traceur', e.message, {
		fileName: file.path,
		showStack: false
}));
```

**Comment by towa48** [comment]
#68

**Comment by towa48** [comment]
pull request #68
